### ISSUE TITLE
Should place long function at the end

### ISSUE THREAD

**Issue by akiradeveloper** [siburu/yaml-parser#1]
Readability advice. If I could tell you this in Twitter..

``` ocaml
  List.iteri ~f:(fun i v ->
      if i > 0 then
        output_string outc ", ";
      output_value outc v) arr;
```

Code like this should swap the `f` and `arr` for readability. Analogue to Haskell's `mapM` and `forM`. (see https://mail.haskell.org/pipermail/beginners/2010-August/005068.html)

However, I don't know if you can swap the two and then compile :) But AFAIK, the `~f` is named parameter that could be placed anywhere.

**Comment by siburu** [comment]
Thank you for reviewing my code.
I agreed with your advice (it still compiles after parameters swap) and pushed the fixed version.
